"""File and directory management utilities for gfpipeline."""

from __future__ import annotations

import logging
from pathlib import Path

from gfpipeline.config.schema import PipelineConfig

log = logging.getLogger(__name__)


class FileManager:
    """Manages output paths and directory creation for the pipeline."""

    def __init__(self, config: PipelineConfig):
        self.proj = config.project_name
        self.data_dir = Path(config.data_dir)
        self.result_dir = Path(config.result_dir)
        self._config = config

    # ------------------------------------------------------------------
    # Derived paths for genome-db generated files
    # ------------------------------------------------------------------

    @property
    def _genome_name(self) -> str:
        return self._config.genome_db.genome_name or self.proj

    @property
    def _rep_dir(self) -> Path:
        return Path(self._config.genome_db.rep_index_dir).resolve()

    @property
    def rep_pep(self) -> Path:
        """Path to representative protein FASTA (generated by genome-db rep-index)."""
        return self._rep_dir / f"{self._genome_name}.rep.pep.fa"

    @property
    def rep_cds(self) -> Path:
        """Path to representative CDS FASTA (generated by genome-db rep-index)."""
        return self._rep_dir / f"{self._genome_name}.rep.cds.fa"

    @property
    def blast_db_prefix(self) -> str:
        """BLAST database prefix derived from rep_pep path."""
        return str(self.rep_pep)

    # ------------------------------------------------------------------
    # Core path helpers
    # ------------------------------------------------------------------

    def result(self, stage: str, type_: str, ext: str) -> Path:
        """Return result_dir/{Proj_Name}.{stage}.{type}.{ext} path."""
        filename = f"{self.proj}.{stage}.{type_}.{ext}"
        return self.result_dir / filename

    def data(self, name: str) -> Path:
        """Return data_dir/{name} path."""
        return self.data_dir / name

    def ensure_dirs(self) -> None:
        """Create data_dir and result_dir (exist_ok=True)."""
        self.data_dir.mkdir(parents=True, exist_ok=True)
        self.result_dir.mkdir(parents=True, exist_ok=True)

    def skip_if_exists(self, path: Path, force: bool) -> bool:
        """Return True (skip) if file exists and force=False, else False."""
        if path.exists() and not force:
            log.info("Skipping %s (already exists)", path)
            return True
        return False


class RefineFileManager(FileManager):
    """FileManager variant that prefixes all stage names with 'refine.'."""

    def result(self, stage: str, type_: str, ext: str) -> Path:
        return super().result(f"refine.{stage}", type_, ext)
